include theos/makefiles/common.mk

BUNDLE_NAME = toggle
toggle_FILES = Switch.x
toggle_FRAMEWORKS = UIKit
toggle_LIBRARIES = flipswitch
toggle_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk